---
apiVersion: v2
name: my-vault-secrets-operator
description: Wrapper chart to deploy HashiCorp Vault Secrets Operator
version: 0.1.0

dependencies:
  - name: vault-secrets-operator
    version: "0.9.0"
    repository: "https://helm.releases.hashicorp.com"
